Added code for manual approval of terraform apply

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,12 +11,23 @@ on:
     - main
     paths:
     - terraform/**
+  workflow_dispatch:
+    inputs:
+      approve_deployment:
+        description: 'Approve deployment to production'
+        required: true
+        default: 'no'
+        type: choice
+        options:
+          - yes
+          - no
 
 env: 
   TF_LOG: INFO
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
+
 
 jobs:
   terraform:
@@ -55,32 +66,21 @@ jobs:
         run: terraform plan -no-color -input=false
         continue-on-error: true
       
-      - uses: actions/github-script@v6
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            <details><summary>Show Plan</summary>
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
-            </details>
-            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
       - name: Terraform Plan Status
         if: steps.plan.outcome == 'failure'
         run: exit 1
+
+      - name: Request manual approval
+        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        run: echo "Manual approval required to proceed."
+
+      - name: Wait for manual approval
+        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        run: |
+          if [[ "${{ github.event.inputs.approve_deployment }}" != "yes" ]]; then
+            echo "Deployment not approved."
+            exit 1
+          fi
 
       - name: Terraform Apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
